### PR TITLE
created manifest file so cgran.org isn't blank for this OOT, feel free to add stuff

### PR DESCRIPTION
**Pull request by 777arc**

### CODE REVIEW

**Comment by straithe** [comment]
Can you please update the website mentioned at the bottom of your changes to point to this repository?

**Comment by 777arc** [comment]
> Can you please update the website mentioned at the bottom of your changes to point to this repository?

done

**Review by grvvy — APPROVED** [review]

**Review by straithe — APPROVED** [review]
Looks good!

**Comment by straithe** [comment]
Thank you for your work!

**Pull request merged**
